name: staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      ######
      ######
      # SSH 設定
      # https://github.com/girishpn/ssh-key-action-1
      # ssh-keygen -p -m PEM -f ~/.ssh/id_rsa
      # で OPENSSH 形式に変換する必要あり
      - name: general0
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_GENERAL0_PRIVATE_KEY }}
          name: general0.key
          known_hosts: ${{ secrets.SSH_GENERAL0_KNOWN_HOSTS }}
          config: |
            Host general0
              HostName ${{ secrets.SSH_GENERAL0_HOST_NAME }}
              User ${{ secrets.SSH_GENERAL0_USER }}
              IdentityFile ~/.ssh/general0.key
              Port 10022
              StrictHostKeyChecking no
      ######
      ######
      - name: Connect server to staging, Other ( pull, build etc... )
        run: |
          ssh general0 \
          "\
            pwd && \
            ls && \
            cd ~/ && \
            git reset --hard HEAD && \
            git checkout staging && \
            git pull && \
            yarn && \
            yarn build
          "
